# docker-compose.yml for local development
services:
  db:
    image: postgres:13
    container_name: postgres_wildfire
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wildfiredb
    ports: # This exposes the port so you can connect from your PC
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wildfire-net

  app:
    build: . # This tells it to use the Dockerfile in the current folder
    container_name: fastapi_wildfire
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app # This links your code so changes are instant
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on: # This waits for the database to start first
      - db
    networks:
      - wildfire-net

volumes:
  postgres_data:

networks:
  wildfire-net: